#spring:
#  application:
#    name: Design
#  datasource:
#    url: "jdbc:mysql://localhost:3306/designs"
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: create
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#    properties:
#      hibernate:
#        format_sql: true
#
#server:
#  port: 8000
#
spring:
  application:
    name: Design
  datasource:
    url: "jdbc:mysql://localhost:3306/designs"
    username: root
    password: Codingmart@123
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000

